greenenjoy_core:
    resource: "@GreenenjoyCoreBundle/Resources/config/routing.yml"
    prefix:   /

greenenjoy_security:
    resource: "@GreenenjoySecurityBundle/Resources/config/routing.yml"
    prefix:   /
    #type: annotation