greenenjoy_post:
    resource: "@GreenenjoyPostBundle/Controller/"
    type: annotation

greenenjoy_core:
    resource: "@GreenenjoyCoreBundle/Controller/"
    type: annotation

greenenjoy_security:
    resource: "@GreenenjoySecurityBundle/Controller/"
    type: annotation

logout:
    path: /logout