greenenjoy_login:
    path: /login
    defaults:
        _controller: GreenenjoySecurityBundle:Security:login

greenenjoy_login_check:
    path: /login_check

greenenjoy_logout:
    path: /logout

greenenjoy_recovery:
    path: /recovery
    defaults:
        _controller: GreenenjoySecurityBundle:Security:recovery

greenenjoy_reset_password:
    path: /reset-password
    defaults:
        _controller: GreenenjoySecurityBundle:Security:resetPassword