greenenjoy_add_post:
    path: /dashboard/add
    defaults:
        _controller: GreenenjoyPostBundle:Post:add

greenenjoy_view_post:
    path: /posts/{categorie}/{title}
    defaults:
        _controller: GreenenjoyPostBundle:Post:view

greenenjoy_like:
    path: /like
    defaults:
        _controller: GreenenjoyPostBundle:Post:like

greenenjoy_report:
    path: /report
    defaults:
        _controller: GreenenjoyPostBundle:Comment:report

greenenjoy_reported:
    path: /dashboard/reported
    defaults:
        _controller: GreenenjoyPostBundle:Comment:reported

greenenjoy_authorize_comment:
    path: /dashboard/reported/authorize
    defaults:
        _controller: GreenenjoyPostBundle:Comment:authorize

greenenjoy_delete_comment:
    path: /dashboard/reported/delete
    defaults:
        _controller: GreenenjoyPostBundle:Comment:delete