greenenjoy_add_post:
    path: /dashboard/add
    defaults:
        _controller: GreenenjoyPostBundle:Post:add

greenenjoy_view_post:
    path: /posts/{categorie}/{title}
    defaults:
        _controller: GreenenjoyPostBundle:Post:view