<?php

namespace Greenenjoy\PostBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getReported()
	{
		$queryBuilder = $this->createQueryBuilder('c');
		$queryBuilder->where('c.reported > 0')->orderBy('c.reported', 'DESC');
		$reported = $queryBuilder->getQuery()->getArrayResult();

		return $reported;
	}
}
