greenenjoy_homepage:
    path:     /
    defaults: 
        _controller: GreenenjoyCoreBundle:Core:index

greenenjoy_dashboard:
    path: /dashboard
    defaults:
        _controller: GreenenjoyCoreBundle:Core:dashboard

greenenjoy_bycategorie:
    path: /posts/{categorie}
    defaults:
        _controller: GreenenjoyCoreBundle:Core:byCategorie