services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    greenenjoy.email.mailing:
        class: Greenenjoy\CoreBundle\Email\Mailing
        arguments:
            - "@mailer"
            - "%mailer_user%"